# Generated by Django 2.2.1 on 2019-05-05 07:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShowRoom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('logo', models.CharField(max_length=350)),
            ],
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manufactor', models.CharField(max_length=100)),
                ('tagline', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=50)),
                ('mileage', models.FloatField()),
                ('year', models.IntegerField()),
                ('status', models.BooleanField()),
                ('transmission', models.CharField(choices=[('Manual', 'Manual'), ('Automatic', 'Automatic')], max_length=50)),
                ('price', models.IntegerField()),
                ('horse_power', models.IntegerField()),
                ('propellant', models.CharField(max_length=100)),
                ('showroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='car_showroom', to='car_api.ShowRoom')),
            ],
        ),
    ]
