# Generated by Django 2.2.1 on 2019-05-07 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='showroom',
            name='logo',
            field=models.CharField(max_length=3550),
        ),
    ]
